$terminal = kitty
$fileManager = thunar
$menu = rofi -show-icons -show drun
# $webBrowser = flatpak run app.zen_browser.zen 
# $webBrowser = firefox
$webBrowser = vivaldi
$musicPlayer = /hdd/bin/aonsoku
$notifDaemon = dunst
