# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Set Pavucontrol as a floating window
windowrule = float on, size 1000 1000, match:class org.pulseaudio.pavucontrol

# Sublime text config as floating windows
# Keymap
windowrule = float on, size 2000 1000, match:class sublime_text, match:title (.*)(\.sublime-keymap)(.*)
# Settings
windowrule = float on, size 2000 1000, match:class sublime_text, match:title (.*)(\.sublime-settings)(.*)

# Vivaldi Settings
windowrule = float on, size 800 800, match:class vivaldi-stable, match:title (Réglages)(.*)

# Strawberry Settings
windowrule = float on, size 800 800, match:class Strawberry, match:title (Modifier la description de la piste)(.*)

# No initial focus
windowrule = no_initial_focus on, workspace 10, match:class Spotify
windowrule = no_initial_focus on, workspace 10, match:class Aonsoku

# Apps on workspace 9
windowrule = workspace 9, match:class discord

# Apps on workspace 10
windowrule = workspace 10, match:class Spotify
windowrule = workspace 10, match:class org.clementine_player.Clementine
windowrule = workspace 10, match:class Aonsoku
windowrule = workspace 10, match:class org.strawberrymusicplayer.strawberry, match:title (!Modifier la description de la piste)(.*)
