## OLD VERSION
# preload = /home/rekkylaws/Images/wallpaper/3440x1440/rainbow_astronaut.jpg
# wallpaper = , /home/rekkylaws/Images/wallpaper/3440x1440/rainbow_astronaut.jpg

wallpaper {
  monitor = DP-1
  path = ~/Images/wallpaper/3440x1440/rainbow_astronaut.jpg
  fit_mode = cover
}

splash = false
